### ISSUE TITLE
Warning loading server extension

### ISSUE THREAD

**Issue by pacospace** [jupyterlab/extension-examples#143] opened 2021-02-05 09:38 UTC
Good morning,

I have issue enabling the server extension app:

step 1
```
pip install jupyterlab-requirements
jupyter lab build
```
step 2
```
jupyter serverextension list

config dir: .local/share/virtualenvs/test-xEaUW4qa/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 3.0.7 OK
    jupyterlab_requirements  enabled 
    - Validating...
Error loading server extension jupyterlab_requirements
      X is jupyterlab_requirements importable?
```

I followed all documentation but I cannot find the reason why it's not validated:

```
[W 2021-02-05 10:40:05.727 ServerApp] The module 'jupyterlab_requirements' could not be found. Are you sure the extension is installed?
```

Refernce repo: https://github.com/thoth-station/jupyterlab-requirements

**Comment by jasongrout** [comment] 2021-02-05 09:44
Have you tried filing an issue with that project?

**Comment by pacospace** [comment] 2021-02-05 09:46
> Have you tried filing an issue with that project?

I'm the maintainer of the project :) 

If I start jupyter lab I do see the extension working by the way:

![Screenshot from 2021-02-05 10-45-11](https://user-images.githubusercontent.com/27498679/107017343-47620800-679f-11eb-943b-a2ad315904e5.png)

maybe it is just jupyter command reading from wrong path?

**Comment by jasongrout** [comment] 2021-02-05 09:57
Assuming you are running the `notebook` server (not `jupyter-server`), this looks like the relevant validation code. That may give some hints about what to look for as the cause: https://github.com/jupyter/notebook/blob/18e4834b12c147f6472a5dfcd6e33345858fd1bb/notebook/serverextensions.py#L77-L121

**Comment by jasongrout** [comment] 2021-02-05 10:01
Perhaps because https://github.com/thoth-station/jupyterlab-requirements/blob/1b8746c1885d5c19f332d1750146660d9a992bc4/jupyterlab_requirements/__init__.py#L45 starts with an underscore (which is the convention in Jupyter Server, but not Jupyter Notebook, so if you are running from Jupyter Notebook, you probably need to remove the leading underscore)

**Comment by pacospace** [comment] 2021-02-05 10:30
> Assuming you are running the `notebook` server (not `jupyter-server`), this looks like the relevant validation code. That may give some hints about what to look for as the cause: https://github.com/jupyter/notebook/blob/18e4834b12c147f6472a5dfcd6e33345858fd1bb/notebook/serverextensions.py#L77-L121

Maybe I'm confused about the two server solutions.  

The extension creates kernels optimized (with AI) for the user for the specific notebook they are working on based on the runtime environment detected and the dependencies with runtime will also be stored in the notebook metadata for reproducibility and portability.

So I would like data scientists to do not worry about these things but to install dependencies correctly so they can share with other safely, allowing reproducibility.

The main target is using jupyterlab locally or using jupyterlab spawn from jupyterhub for now.

**Comment by pacospace** [comment] 2021-02-05 10:33
> Perhaps because https://github.com/thoth-station/jupyterlab-requirements/blob/1b8746c1885d5c19f332d1750146660d9a992bc4/jupyterlab_requirements/__init__.py#L45 starts with an underscore (which is the convention in Jupyter Server, but not Jupyter Notebook, so if you are running from Jupyter Notebook, you probably need to remove the leading underscore)

I had a look at another extension to compare what I was doing: https://github.com/jupyterlab/jupyterlab-git/blob/3c28978d8c6fc5ca6376e37c259a85368e4de9bf/jupyterlab_git/__init__.py#L45 so your comment help, I could not find that difference in the docs.

**Comment by jasongrout** [comment] 2021-02-05 10:39
https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html#extensionapp-as-a-classic-notebook-server-extension hints at the difference

**Comment by pacospace** [comment] 2021-02-05 10:43
> https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html#extensionapp-as-a-classic-notebook-server-extension hints at the difference

Thank you very much @jasongrout!!

**Comment by jasongrout** [comment] 2021-02-05 17:51
Closing as resolved. In the future, it probably would have been better to open an issue on the Jupyter notebook repo or the Jupyter Server repo. Thanks!

**Closed by jasongrout** 2021-02-05 17:51 UTC

**Comment by pacospace** [comment] 2021-02-11 11:46
> https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html#extensionapp-as-a-classic-notebook-server-extension hints at the difference

sorry @jasongrout  Is it `_jupyter_server_extension_points?` or `_jupyter_server_extension_paths?`
Because server extension example shows the second: https://github.com/jupyterlab/extension-examples/blob/0254ccbf26c1da0dfe4bb2840d3717504108bf64/advanced/server-extension/jlab_ext_example/__init__.py#L19

**Comment by pacospace** [comment] 2021-02-11 12:12
Moreover there is https://github.com/jupyterlab/extension-examples/blob/0254ccbf26c1da0dfe4bb2840d3717504108bf64/advanced/server-extension/setup.py#L39 which is different from stated in 

> https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html#extensionapp-as-a-classic-notebook-server-extension hints at the difference

**Comment by fcollonval** [comment] 2021-02-11 16:24
Thanks for the question, I learn something ;)

> Is it `_jupyter_server_extension_points` or `_jupyter_server_extension_paths`?

According the code is should be `_jupyter_server_extension_points`. The other one is the to-be-removed name.

https://github.com/jupyter-server/jupyter_server/blob/3220f4f79e58b7f377cec7416bd35ad0ea300fb2/jupyter_server/extension/utils.py#L53

**Comment by fcollonval** [comment] 2021-02-11 16:27
> which one should be followed?

They have identical result. In the example the helper `jupyter-packaging` package is used. Its syntax to define python data files is a bit different as you find out. But the results is the same, the JSON file activating the server extension needs to be copied in `/jupyter/jupyter_server_config.d`.

I advice you to follow the example syntax.

**Comment by pacospace** [comment] 2021-02-11 16:44
> > which one should be followed?
> 
> They have identical result. In the example the helper `jupyter-packaging` package is used. Its syntax to define python data files is a bit different as you find out. But the results is the same, the JSON file activating the server extension needs to be copied in `/jupyter/jupyter_server_config.d`.
> 
> I advice you to follow the example syntax.

Thanks @fcollonval! Unfortunately, I still cannot have the backend part working, I tested many ways but still when I install it `pip install jupyterlab-requirements`  and then run `jupyter lab build` the new endpoints created do not work, giving 404.

https://github.com/thoth-station/jupyterlab-requirements/blob/master/jupyterlab_requirements/__init__.py 

```
config dir: /home/fmurdaca/.local/share/virtualenvs/elyra-aidevsecops-tutorial-6AvpO_pA/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 3.0.7 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.23.3 OK
    jupyterlab_requirements  enabled 
    - Validating...
Error loading server extension jupyterlab_requirements
      X is jupyterlab_requirements importable?
    nbdime  enabled 
    - Validating...
      nbdime 2.1.0 OK
```

**Comment by pacospace** [comment] 2021-02-11 18:45
also isn't https://github.com/jupyterlab/extension-examples/blob/0254ccbf26c1da0dfe4bb2840d3717504108bf64/advanced/server-extension/jlab_ext_example/__init__.py#L23 supposed to be `serverapp: jupyter_server.serverapp.ServerApp`? @fcollonval

**Comment by pacospace** [comment] 2021-02-11 19:46
ok found the solution finally!! Thanks again @fcollonval @jasongrout the extension is finally ready for users to be installed correctly!
